kind: Pod
apiVersion: v1
metadata:
  generateName: stress-cpu-server-inf7-
  labels:
    app: stress-cpu-server-inf7
spec:
  containers:
    - name: stress-cpu
      image: 'quay.io/dfroehli/tools-stress:latest'
      env:
        - name: STRESS_ARGS
          value: '--cpu 22'
      resources:
        requests:
          cpu: 22
          memory: 1024Mi
        limits:
          cpu: 22
          memory: 1024Mi
      imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: inf7
  tolerations:
  - key: "node.kubernetes.io/unschedulable"
    operator: "Exists"
    effect: "NoSchedule"
